### ISSUE TITLE
at_c: atclient put

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_c#133]
atProtocol put operation:

- According to the type of AtKey, certain things need to happen.
- Generally all types will use update:
- Also make sure to utilize atclient_atkey_metadata_to_protocolstr to prepend the update command with metadata for the atkey
- Some of this work is held up by #142 

shared atkey:
- encrypt the value with an existing shared aes encryption key if it exists, or create a new one if it does not exist

public key:
- no encryption needed

self key:
- simply use selfEncryptionKey which can be found in the `atclient.atkeys` struct.
```[tasklist]
### Tasks
- [ ] shared atkey @JeremyTubongbanua 
- [x] public key @JeremyTubongbanua 
- [x] self key @JeremyTubongbanua 
```

**Comment by JeremyTubongbanua** [comment]
@realvarx Hey, since you are doing work on _get_sharedkey, would it be okay to assign you to the sharedkey portion of _put ?

**Comment by JeremyTubongbanua** [comment]
Bumping up to P1 because it's blocking release

**Comment by xavierchanth** [comment]
We don't have a release cycle yet, hence why I made it P2.
