### ISSUE TITLE
at_c: rename len to capacity(/size?)

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#140]
# Discussion

@XavierChanth @realvarx and @JeremyTubongbanua briefly discussed renaming `len` to `capacity` (or even `size`).

That is because `len` can be confused of being either the allocated buffer size  or the length of the value that is stored in the buffer.

For example:
```c
char command[32] = {0};
strcpy(command, "123");

// 'len' should be 32
// and olen is 3
```

# Tasks
Depending on what we decide on renaming it to, the tasks associated with this ticket and the allocated sprint points correspond to:
- [ ] Refactor `len` in `atstr.h`
- [ ] Refactor `len` in `atbytes.h`
- [ ] Refactor `len` in all atchops functions

# Appendix:

Some examples of when we use `len` that may be confusing

atbytes.h
```c
typedef struct atclient_atbytes {
  unsigned long len;    // the allocated length of the buffer
  unsigned char *bytes; // the buffer of bytes (pointer to the first byte in the buffer on the heap)
  unsigned long olen;   // the output length of the buffer
} atclient_atbytes;
```

atbytes.c
```
typedef struct atclient_atstr {
  unsigned long len;  // buffer length
  char *str;          // string
  unsigned long olen; // output length (length of string)
} atclient_atstr;
```

**Comment by JeremyTubongbanua** [comment]
@XavierChanth @realvarx would like to bring up the discussion on renaming `len` of our buffer structures here.

@XavierChanth you mentioned `capacity`

I personally believe in `size` to stay consistent with what C calls stuff

**Comment by xavierchanth** [comment]
but size/capacity is vector terminology, I was using it as an example. The industry still typically uses length for string - e.g. std::string has .length and .size for this exact reason. Maybe I'm biased based on the programming languages I use, but if I want string length I expect it to be length or len.

**Comment by JeremyTubongbanua** [comment]
> but size/capacity is vector terminology, I was using it as an example. The industry still typically uses length for string - e.g. std::string has .length and .size for this exact reason. Maybe I'm biased based on the programming languages I use, but if I want string length I expect it to be length or len.

Ok, so maybe we should do:

`size` for allocated buffer length
`olen` for the output length

**Comment by JeremyTubongbanua** [comment]
We will be going with `size` - allocated buffer length, `len` for output length (where you expect something like str.len to return the actual length of the string like "hello" would be of length 5, but the `size` could be something like `6` to include the null terminator, or even `1024` if a lot was allocated).
