### ISSUE TITLE
at_c: Breaking Changes Tracker

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_c#155]
```[tasklist]
### Breaking Changes to make
- [ ] https://github.com/atsign-foundation/at_c/issues/154
- [ ] https://github.com/atsign-foundation/at_c/issues/140
- [ ] https://github.com/atsign-foundation/at_c/issues/225
- [ ] https://github.com/atsign-foundation/at_c/issues/127
- [ ] https://github.com/atsign-foundation/at_c/issues/128
- [ ] https://github.com/atsign-foundation/at_c/issues/129
- [ ] https://github.com/atsign-foundation/at_c/issues/284
- [ ] https://github.com/atsign-foundation/at_c/issues/375
- [ ] https://github.com/atsign-foundation/at_c/issues/377
```

**Comment by xavierchanth** [comment]
We should try to do these before the initial release, but after a majority of the development effort has been made. We don't want to break other people's work, but we also don't want to break our own.

**Comment by JeremyTubongbanua** [comment]
Added #225

**Comment by JeremyTubongbanua** [comment]
Reopening this issue to track:
#375  #377
