### ISSUE TITLE
at_c: Pkam Changes Tracker

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#160]
@JeremyTubongbanua and @realvarx are currently taking on some changes in the atclient_pkam_authenticate function:

```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/at_c/issues/141 - @realvarx 
- [ ] https://github.com/atsign-foundation/at_c/issues/142 - @realvarx 
- [ ] https://github.com/atsign-foundation/at_c/issues/119 - @realvarx 
- [ ] https://github.com/atsign-foundation/at_c/issues/161 - @realvarx 
```

**Comment by JeremyTubongbanua** [comment]
This is done
