### ISSUE TITLE
at_c: functional tests - crud

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#177]
Functional tests for CRUD operations

```[tasklist]
### Tasks
- [x] Put selfkey
- [x] Put sharedkey that was created by us with another atSign
- [x] Put publickey
- [x] Get selfkey (that was created by this functional test suite)
- [x] Get sharedkey that was shared by us with another atSign (that was created by this functional test suite)
- [x] Get sharedkey that was shared by another atSign with us (that was created by this functional test suite)
- [x] Get publickey (that was created by this functional test suite)
- [x] Delete selfkey
- [x] Delete sharedkey 1
- [x] Delete sharedkey 2
- [x] Delete publickey
```
