### ISSUE TITLE
at_c: atchops function parameters should take non-base64

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#182]
This is the function header for AES CTR decrypt in atchops

`int atchops_aesctr_decrypt(const char *keybase64, const size_t keybase64len, const enum atchops_aes_size keybits,
                           unsigned char *iv, const unsigned char *ciphertextbase64,
                           const size_t ciphertextbase64len, unsigned char *plaintext,
                           const size_t plaintextlen, size_t *plaintextolen)`

In hindsight, this function shouldn't take any base64 input. In this case, it should take a raw `unsigned char *key` as well as raw `ciphertext`. Leave it up to the developer to base64 encode it for finer error handling and to make this function more atomic.

This also leaves room for optimization (5 subsequent AES decrypts in `atkeys.c` will be decoding the AES key 5 times when you really only need to decode the AES key once).

Task List:

```[tasklist]
### Tasks
- [x] AES CTR Encrypt/Decrypt functions
- [ ] RSA Encrypt/Decrypt
- [ ] RSA Sign/Verify
```

**Comment by JeremyTubongbanua** [comment]
@realvarx agrees 

and suggests "`encrypt_bytes or encrypt_b64 calls -> static encrypt/decrypt`"
