### ISSUE TITLE
at_c: atclient CRUD Operations Tracker

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#39]
```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/at_c/issues/135
- [ ] https://github.com/atsign-foundation/at_c/issues/136
- [ ] https://github.com/atsign-foundation/at_c/issues/133
- [ ] https://github.com/atsign-foundation/at_c/issues/132
- [ ] https://github.com/atsign-foundation/at_c/issues/134
- [ ] #150 
- [ ] https://github.com/atsign-foundation/at_c/issues/165
```

**Comment by ksanty** [comment]
Need this in order to prepare for demo in Jan

**Comment by JeremyTubongbanua** [comment]
Update: pkam authentication working, the following work was completed to achieve this: atsign struct, atkeys struct, atkeysfile struct

To get the rest of the atclient functionality ready, an AtKey struct and Metadata struct and corresponding functions (such as atclient_atkey_from_string(char *str) needs to be created)

**Comment by JeremyTubongbanua** [comment]
More work has been done in #42 (such as metadata, atkey) for atclient functions

**Comment by JeremyTubongbanua** [comment]
This ticket depends on #44 to be completed first

**Comment by JeremyTubongbanua** [comment]
Picking this up now

**Comment by JeremyTubongbanua** [comment]
#150 has been added to the task list

**Comment by xavierchanth** [comment]
Can we close this @JeremyTubongbanua ? I don't think that verb builders is a CRUD thing, but rather an architectural design pattern.
